---
# create a new VM from a template

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 192.168.11.55
    #port: 5480
    vcenter_user: administrator@vsphere.local
    vcenter_pass: Raj#083#
    esxhost: 192.168.11.45
    datastore: datastore1
    vmtemplate: netscalre
    name: "testing"
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: Datacenter
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        folder: /
        guest_id: oracleLinux64Guest
        disk:
          - size_gb: "{{ disk_size | default(30) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: dhcp
        hardware:
          num_cpus: 2
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"
